package mapgen

import (
	"cmp"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/manojpisini/rivu/internal/registry"
)

// defaults are always skipped when listing a project; config's
// scanner.ignore names are merged in on top (M-01: one ignore source).
var defaults = []string{".git", "node_modules", "vendor", "target", "dist", "build", ".venv", ".metadata"}

func skipSet(ignore []string) map[string]bool {
	m := map[string]bool{}
	for _, n := range defaults {
		m[strings.ToLower(n)] = true
	}
	for _, n := range ignore {
		m[strings.ToLower(n)] = true
	}
	return m
}

// Content renders both agent files for p without touching the disk:
// the AGENTS.md body and the full PROJECT_MAP.md body. Build and
// Status share it so "what would change" always matches "what writes".
func Content(p registry.Project, ignore []string) (agentsBody, mapBody string) {
	purpose := readmePurpose(p.Path)
	agentsPurpose := purpose
	if agentsPurpose == "" {
		agentsPurpose = "See `../overview.md`."
	}
	agentsBody = fmt.Sprintf("# Agent Instructions for %s\n\n## Read first\n1. `PROJECT_MAP.md`\n2. `../overview.md`\n3. `../tasks.md`\n4. `../decisions.md`\n\n## Project purpose\n%s\n\n## Important rules\n- Preserve the Bank (`.metadata/`).\n- Prefer small, tested changes.\n- Do not modify generated or vendor directories.\n\n## Ignore by default\n`.git`, `node_modules`, `vendor`, `target`, `dist`, `build`, caches.\n\n## Safe commands\nInspect project scripts and configuration before executing commands.\n", p.Name, agentsPurpose)
	skip := skipSet(ignore)
	files, dirs := rankedInventory(p.Path, skip)
	mapPurpose := purpose
	if mapPurpose == "" {
		mapPurpose = "See `.metadata/overview.md`."
	}
	stack := strings.Join(p.Stack, ", ")
	if m := goModule(p.Path); m != "" {
		if stack == "" {
			stack = "module `" + m + "`"
		} else {
			stack += ", module `" + m + "`"
		}
	}
	if stack == "" {
		stack = "Not detected"
	}
	// spec 4.4 rule 6 / M-03: secret files are named, never read.
	doNotRead := "## Do not read / never commit\n- `.env*`, `*.pem`, `id_rsa*`, `*.key`, `secrets.*` — never read or commit\n"
	if found := secretNames(p.Path); len(found) > 0 {
		doNotRead += "- Detected here (names only): `" + strings.Join(found, "`, `") + "`\n"
	}
	body := fmt.Sprintf("# Project Map: %s\n\n## Purpose\n%s\n\n## Stack\n%s\n\n## Scripts and targets\n%s\n\n## Important files\n%s\n\n## Important directories\n%s\n\n## Generated/vendor directories\n`.git`, `node_modules`, `vendor`, `target`, `dist`, `build`, caches.\n\n%s\n## Suggested first-read order\n1. README and manifest files\n2. Source entrypoints\n3. Tests\n4. Build and CI configuration\n", p.Name, mapPurpose, stack, list(scriptsAndTargets(p.Path)), list(files), list(dirs), doNotRead)
	sum := sha256.Sum256([]byte(body))
	mapBody = fmt.Sprintf("<!-- generated by rivu - do not edit -->\n<!-- content-hash: %x -->\n%s", sum[:8], body)
	return agentsBody, mapBody
}

// Entry, manifest, CI, build and test names rank first in the listings
// (M-02); everything else follows alphabetically. Matching is
// case-insensitive so Makefile/makefile and Gemfile/gemfile agree.
var (
	manifestFiles = map[string]bool{"go.mod": true, "go.work": true, "package.json": true, "cargo.toml": true, "pyproject.toml": true, "requirements.txt": true, "setup.py": true, "gemfile": true, "composer.json": true, "pom.xml": true, "build.gradle": true, "build.gradle.kts": true}
	ciFiles       = map[string]bool{".gitlab-ci.yml": true, ".travis.yml": true, "jenkinsfile": true, "azure-pipelines.yml": true, "appveyor.yml": true, "bitbucket-pipelines.yml": true}
	buildFiles    = map[string]bool{"makefile": true, "gnumakefile": true, "taskfile.yml": true, "taskfile.yaml": true, "justfile": true, "dockerfile": true, "docker-compose.yml": true, "cmakelists.txt": true}
	testDirs      = map[string]bool{"test": true, "tests": true, "spec": true, "__tests__": true, "e2e": true}
)

type rankItem struct {
	name string
	cls  int
}

// entryFiles finds entrypoints by probing (M-02): cmd/*/main.go,
// src/index.* and top-level main.*. Returns display paths relative to
// the project root.
func entryFiles(root string) []string {
	var out []string
	for _, n := range []string{"main.py", "main.go", "main.js", "main.ts"} {
		if isFile(filepath.Join(root, n)) {
			out = append(out, n)
		}
	}
	if ents, err := os.ReadDir(filepath.Join(root, "src")); err == nil {
		for _, e := range ents {
			if !e.IsDir() && strings.HasPrefix(e.Name(), "index.") {
				out = append(out, "src/"+e.Name())
			}
		}
	}
	if ents, err := os.ReadDir(filepath.Join(root, "cmd")); err == nil {
		for _, e := range ents {
			if e.IsDir() && isFile(filepath.Join(root, "cmd", e.Name(), "main.go")) {
				out = append(out, "cmd/"+e.Name()+"/main.go")
			}
		}
	}
	return out
}

// rankedInventory lists top-level entries with the M-02 ranks applied,
// plus nested entrypoint files that live one level down.
func rankedInventory(root string, skip map[string]bool) (files, dirs []string) {
	entry := map[string]bool{}
	for _, e := range entryFiles(root) {
		entry[e] = true
	}
	var fileItems, dirItems []rankItem
	entries, _ := os.ReadDir(root)
	for _, e := range entries {
		if skip[strings.ToLower(e.Name())] {
			continue
		}
		if e.IsDir() {
			dirItems = append(dirItems, rankItem{name: e.Name() + "/", cls: dirClass(e.Name())})
			continue
		}
		// M-03: secrets never appear as "important" reading.
		if isSecretName(e.Name()) {
			continue
		}
		fileItems = append(fileItems, rankItem{name: e.Name(), cls: fileClass(e.Name(), entry)})
	}
	for e := range entry {
		if !strings.Contains(e, "/") {
			continue // top-level already collected above
		}
		if head, _, _ := strings.Cut(e, "/"); !skip[strings.ToLower(head)] {
			fileItems = append(fileItems, rankItem{name: e, cls: 0})
		}
	}
	return renderRanked(fileItems), renderRanked(dirItems)
}

func fileClass(name string, entry map[string]bool) int {
	switch {
	case entry[name]:
		return 0
	case manifestFiles[strings.ToLower(name)]:
		return 1
	case ciFiles[strings.ToLower(name)]:
		return 2
	case buildFiles[strings.ToLower(name)]:
		return 3
	default:
		return 4
	}
}

func dirClass(name string) int {
	switch n := strings.ToLower(name); {
	case n == "cmd", n == "src":
		return 0
	case n == ".github":
		return 2
	case n == "scripts":
		return 3
	case testDirs[n]:
		return 4
	default:
		return 5
	}
}

func renderRanked(items []rankItem) []string {
	slices.SortFunc(items, func(a, b rankItem) int {
		return cmp.Or(cmp.Compare(a.cls, b.cls), strings.Compare(a.name, b.name))
	})
	out := make([]string, 0, len(items))
	for _, it := range items {
		out = append(out, it.name)
	}
	return out
}

// scriptsAndTargets (M-02) extracts package.json script names and
// Makefile targets so agents can run the project without exploring.
func scriptsAndTargets(root string) []string {
	var out []string
	if b, err := os.ReadFile(filepath.Join(root, "package.json")); err == nil {
		var pj struct {
			Scripts map[string]string `json:"scripts"`
		}
		if json.Unmarshal(b, &pj) == nil {
			for _, name := range slices.Sorted(maps.Keys(pj.Scripts)) {
				out = append(out, "npm run "+name)
			}
		}
	}
	out = append(out, makeTargets(root)...)
	return out
}

// makeTargets collects simple `name:` rules from the first Makefile
// found; ponytail: first 20 targets, recipes and includes skipped by
// leading whitespace/dot/comment — raise the ceiling if real projects
// need more.
func makeTargets(root string) []string {
	var b []byte
	for _, n := range []string{"Makefile", "makefile", "GNUmakefile"} {
		if data, err := os.ReadFile(filepath.Join(root, n)); err == nil {
			b = data
			break
		}
	}
	if b == nil {
		return nil
	}
	var out []string
	seen := map[string]bool{}
	for _, line := range strings.Split(string(b), "\n") {
		if line == "" || line[0] == ' ' || line[0] == '\t' || line[0] == '.' || line[0] == '#' {
			continue
		}
		raw, _, ok := strings.Cut(line, ":")
		if !ok || raw == "" || strings.ContainsAny(raw, " \t=$%+") {
			continue // recipes, variables, pattern rules — targets are one bare word
		}
		if seen[raw] {
			continue
		}
		seen[raw] = true
		out = append(out, "make "+raw)
		if len(out) >= 20 {
			break
		}
	}
	return out
}

// goModule pulls the `module` line out of go.mod (M-02).
func goModule(root string) string {
	b, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(b), "\n") {
		if rest, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			return strings.TrimSpace(rest)
		}
	}
	return ""
}

// readmePurpose (M-02) takes the first prose paragraph of README.md:
// leading headings, badges and image lines are skipped, and the
// paragraph stops at the first blank line or heading. Empty string
// means "no purpose here" — callers fall back to the overview pointer.
func readmePurpose(root string) string {
	b, err := os.ReadFile(filepath.Join(root, "README.md"))
	if err != nil {
		return ""
	}
	var para []string
	for _, line := range strings.Split(string(b), "\n") {
		t := strings.TrimSpace(line)
		if t == "" || strings.HasPrefix(t, "#") {
			if len(para) > 0 {
				break
			}
			continue
		}
		if strings.HasPrefix(t, "[!") || strings.HasPrefix(t, "![") || strings.HasPrefix(t, "<") {
			continue // badges, images, HTML banners
		}
		para = append(para, t)
	}
	p := strings.Join(para, " ")
	if r := []rune(p); len(r) > 240 {
		cut := strings.TrimSpace(string(r[:240]))
		if i := strings.LastIndex(cut, " "); i > 160 {
			cut = cut[:i]
		}
		p = cut + "…"
	}
	return p
}

func isFile(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}

// isSecretName matches the never-read patterns from M-03: `.env*`,
// `*.pem`, `id_rsa*`, `*.key`, `secrets.*`. Matching is by name only —
// nothing here opens the file (spec 4.4 rule 6).
func isSecretName(name string) bool {
	n := strings.ToLower(name)
	if strings.HasPrefix(n, ".env") {
		return true
	}
	for _, pat := range []string{"*.pem", "id_rsa*", "*.key", "secrets.*"} {
		if ok, _ := filepath.Match(pat, n); ok {
			return true
		}
	}
	return false
}

// secretNames returns matching top-level file names, sorted — names
// only, contents are never touched. ponytail: top-level scan only;
// walk non-ignored subdirs if nested secrets become a real concern.
func secretNames(root string) []string {
	entries, _ := os.ReadDir(root)
	var out []string
	for _, e := range entries {
		if !e.IsDir() && isSecretName(e.Name()) {
			out = append(out, e.Name())
		}
	}
	slices.Sort(out)
	return out
}

// Status reports what Build would change without writing anything:
// AGENTS.md missing, or PROJECT_MAP.md differing from a fresh render.
func Status(p registry.Project, ignore []string) (agentsMissing, mapStale bool) {
	_, want := Content(p, ignore)
	if _, err := os.Stat(filepath.Join(p.Path, ".metadata", "agent", "AGENTS.md")); err != nil {
		agentsMissing = true
	}
	prev, err := os.ReadFile(filepath.Join(p.Path, ".metadata", "agent", "PROJECT_MAP.md"))
	return agentsMissing, err != nil || string(prev) != want
}

// Build writes the agent map. AGENTS.md is protected (spec 4.4 rule 4):
// written only when missing, never overwritten. PROJECT_MAP.md is
// machine-owned: regenerated with a header and content hash, but left
// untouched when the content did not change.
func Build(p registry.Project, ignore []string) error {
	d := filepath.Join(p.Path, ".metadata", "agent")
	if err := os.MkdirAll(d, 0755); err != nil {
		return err
	}
	agents, want := Content(p, ignore)
	agentsPath := filepath.Join(d, "AGENTS.md")
	if _, err := os.Stat(agentsPath); err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		if err := os.WriteFile(agentsPath, []byte(agents), 0644); err != nil {
			return err
		}
	}
	mapPath := filepath.Join(d, "PROJECT_MAP.md")
	if prev, err := os.ReadFile(mapPath); err == nil && string(prev) == want {
		return nil
	}
	return os.WriteFile(mapPath, []byte(want), 0644)
}
func list(v []string) string {
	if len(v) == 0 {
		return "- None detected"
	}
	var b strings.Builder
	for _, x := range v {
		b.WriteString("- `" + x + "`\n")
	}
	return strings.TrimSpace(b.String())
}

// Diff compares the on-disk body with a fresh render and returns
// unified-style lines ("  " context, "-" disk, "+" generated) for the
// Map report (P4.15). Empty input is no lines, not one blank line.
func Diff(disk, want string) []string {
	a, b := diffLines(disk), diffLines(want)
	// Trim the common edges first: map bodies share most lines, and the
	// LCS below is O(n*m) over what remains. The trimmed edges still go
	// back into the output as context.
	p := 0
	for p < len(a) && p < len(b) && a[p] == b[p] {
		p++
	}
	s := 0
	for s < len(a)-p && s < len(b)-p && a[len(a)-1-s] == b[len(b)-1-s] {
		s++
	}
	head, tail := a[:p], a[len(a)-s:]
	a, b = a[p:len(a)-s], b[p:len(b)-s]
	m, n := len(a), len(b)
	var mid []string
	if m*n > 4_000_000 {
		// ponytail: replace-all fallback for absurd inputs; upgrade to a
		// Myers diff only if real maps ever hit this ceiling
		mid = make([]string, 0, m+n)
		for _, l := range a {
			mid = append(mid, "- "+l)
		}
		for _, l := range b {
			mid = append(mid, "+ "+l)
		}
	} else {
		lcs := make([][]int, m+1)
		for i := range lcs {
			lcs[i] = make([]int, n+1)
		}
		for i := m - 1; i >= 0; i-- {
			for j := n - 1; j >= 0; j-- {
				if a[i] == b[j] {
					lcs[i][j] = lcs[i+1][j+1] + 1
				} else {
					lcs[i][j] = max(lcs[i+1][j], lcs[i][j+1])
				}
			}
		}
		var i, j int
		for i < m && j < n {
			switch {
			case a[i] == b[j]:
				mid = append(mid, "  "+a[i])
				i, j = i+1, j+1
			case lcs[i+1][j] >= lcs[i][j+1]:
				mid = append(mid, "- "+a[i])
				i++
			default:
				mid = append(mid, "+ "+b[j])
				j++
			}
		}
		for ; i < m; i++ {
			mid = append(mid, "- "+a[i])
		}
		for ; j < n; j++ {
			mid = append(mid, "+ "+b[j])
		}
	}
	out := make([]string, 0, len(head)+len(mid)+len(tail))
	for _, l := range head {
		out = append(out, "  "+l)
	}
	out = append(out, mid...)
	for _, l := range tail {
		out = append(out, "  "+l)
	}
	return out
}

func diffLines(s string) []string {
	if s == "" {
		return nil
	}
	return strings.Split(strings.TrimSuffix(s, "\n"), "\n")
}
