package mapgen

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/manojpisini/rivu/internal/registry"
)

// defaults are always skipped when listing a project; config's
// scanner.ignore names are merged in on top (M-01: one ignore source).
var defaults = []string{".git", "node_modules", "vendor", "target", "dist", "build", ".venv", ".metadata"}

func skipSet(ignore []string) map[string]bool {
	m := map[string]bool{}
	for _, n := range defaults {
		m[strings.ToLower(n)] = true
	}
	for _, n := range ignore {
		m[strings.ToLower(n)] = true
	}
	return m
}

// Content renders both agent files for p without touching the disk:
// the AGENTS.md body and the full PROJECT_MAP.md body. Build and
// Status share it so "what would change" always matches "what writes".
func Content(p registry.Project, ignore []string) (agentsBody, mapBody string) {
	agentsBody = fmt.Sprintf("# Agent Instructions for %s\n\n## Read first\n1. `PROJECT_MAP.md`\n2. `../overview.md`\n3. `../tasks.md`\n4. `../decisions.md`\n\n## Project purpose\nSee `../overview.md`.\n\n## Important rules\n- Preserve the Bank (`.metadata/`).\n- Prefer small, tested changes.\n- Do not modify generated or vendor directories.\n\n## Ignore by default\n`.git`, `node_modules`, `vendor`, `target`, `dist`, `build`, caches.\n\n## Safe commands\nInspect project scripts and configuration before executing commands.\n", p.Name)
	skip := skipSet(ignore)
	var files, dirs []string
	entries, _ := os.ReadDir(p.Path)
	for _, e := range entries {
		if skip[strings.ToLower(e.Name())] {
			continue
		}
		if e.IsDir() {
			dirs = append(dirs, e.Name()+"/")
		} else {
			files = append(files, e.Name())
		}
	}
	sort.Strings(files)
	sort.Strings(dirs)
	stack := strings.Join(p.Stack, ", ")
	if stack == "" {
		stack = "Not detected"
	}
	body := fmt.Sprintf("# Project Map: %s\n\n## Purpose\nSee `.metadata/overview.md`.\n\n## Stack\n%s\n\n## Important files\n%s\n\n## Important directories\n%s\n\n## Generated/vendor directories\n`.git`, `node_modules`, `vendor`, `target`, `dist`, `build`, caches.\n\n## Suggested first-read order\n1. README and manifest files\n2. Source entrypoints\n3. Tests\n4. Build and CI configuration\n", p.Name, stack, list(files), list(dirs))
	sum := sha256.Sum256([]byte(body))
	mapBody = fmt.Sprintf("<!-- generated by rivu - do not edit -->\n<!-- content-hash: %x -->\n%s", sum[:8], body)
	return agentsBody, mapBody
}

// Status reports what Build would change without writing anything:
// AGENTS.md missing, or PROJECT_MAP.md differing from a fresh render.
func Status(p registry.Project, ignore []string) (agentsMissing, mapStale bool) {
	_, want := Content(p, ignore)
	if _, err := os.Stat(filepath.Join(p.Path, ".metadata", "agent", "AGENTS.md")); err != nil {
		agentsMissing = true
	}
	prev, err := os.ReadFile(filepath.Join(p.Path, ".metadata", "agent", "PROJECT_MAP.md"))
	return agentsMissing, err != nil || string(prev) != want
}

// Build writes the agent map. AGENTS.md is protected (spec 4.4 rule 4):
// written only when missing, never overwritten. PROJECT_MAP.md is
// machine-owned: regenerated with a header and content hash, but left
// untouched when the content did not change.
func Build(p registry.Project, ignore []string) error {
	d := filepath.Join(p.Path, ".metadata", "agent")
	if err := os.MkdirAll(d, 0755); err != nil {
		return err
	}
	agents, want := Content(p, ignore)
	agentsPath := filepath.Join(d, "AGENTS.md")
	if _, err := os.Stat(agentsPath); err != nil {
		if !os.IsNotExist(err) {
			return err
		}
		if err := os.WriteFile(agentsPath, []byte(agents), 0644); err != nil {
			return err
		}
	}
	mapPath := filepath.Join(d, "PROJECT_MAP.md")
	if prev, err := os.ReadFile(mapPath); err == nil && string(prev) == want {
		return nil
	}
	return os.WriteFile(mapPath, []byte(want), 0644)
}
func list(v []string) string {
	if len(v) == 0 {
		return "- None detected"
	}
	var b strings.Builder
	for _, x := range v {
		b.WriteString("- `" + x + "`\n")
	}
	return strings.TrimSpace(b.String())
}
