package mapgen

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/manojpisini/rivu/internal/registry"
)

var update = flag.Bool("update", false, "rewrite golden files")

func fixture(t *testing.T) registry.Project {
	t.Helper()
	root := t.TempDir()
	for _, f := range []string{"main.go", "README.md"} {
		if err := os.WriteFile(filepath.Join(root, f), []byte("package x\n"), 0644); err != nil {
			t.Fatal(err)
		}
	}
	for _, d := range []string{"cmd", ".git", "scratch"} {
		if err := os.MkdirAll(filepath.Join(root, d), 0755); err != nil {
			t.Fatal(err)
		}
	}
	return registry.Project{Name: "Golden", Slug: "golden", Path: root, Stack: []string{"go"}}
}

func TestBuildPreservesAgentsMD(t *testing.T) {
	p := fixture(t)
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	agents := filepath.Join(p.Path, ".metadata", "agent", "AGENTS.md")
	if err := os.WriteFile(agents, []byte("hand-written rules"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(agents)
	if string(got) != "hand-written rules" {
		t.Errorf("AGENTS.md overwritten: %q", got)
	}
}

func TestProjectMapHeaderHashAndSkipRewrite(t *testing.T) {
	p := fixture(t)
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	mapPath := filepath.Join(p.Path, ".metadata", "agent", "PROJECT_MAP.md")
	first, err := os.ReadFile(mapPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(first), "<!-- generated by rivu - do not edit -->\n<!-- content-hash: ") {
		t.Errorf("missing generated header: %q", string(first[:80]))
	}
	// Unchanged content: no rewrite.
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	second, _ := os.ReadFile(mapPath)
	if string(second) != string(first) {
		t.Error("unchanged map was rewritten")
	}
	// Changed content: rewritten with a new hash.
	if err := os.WriteFile(filepath.Join(p.Path, "new.go"), []byte("package x\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	third, _ := os.ReadFile(mapPath)
	if string(third) == string(first) {
		t.Error("map did not update after project changed")
	}
}

func TestStatusMirrorsBuild(t *testing.T) {
	p := fixture(t)
	missing, stale := Status(p, nil)
	if !missing || !stale {
		t.Errorf("before build: missing=%v stale=%v, want both true", missing, stale)
	}
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	if missing, stale = Status(p, nil); missing || stale {
		t.Errorf("after build: missing=%v stale=%v, want both false", missing, stale)
	}
	if err := os.WriteFile(filepath.Join(p.Path, "extra.go"), []byte("package x\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if _, stale = Status(p, nil); !stale {
		t.Error("new file did not make the map stale")
	}
	// Status never writes.
	agents := filepath.Join(p.Path, ".metadata", "agent", "AGENTS.md")
	if err := os.Remove(agents); err != nil {
		t.Fatal(err)
	}
	if missing, _ = Status(p, nil); !missing {
		t.Error("missing AGENTS.md not reported")
	}
	if _, err := os.Stat(agents); err == nil {
		t.Error("Status wrote AGENTS.md")
	}
}

func TestBuildSharesIgnoreList(t *testing.T) {
	p := fixture(t)
	if err := Build(p, []string{"scratch"}); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(filepath.Join(p.Path, ".metadata", "agent", "PROJECT_MAP.md"))
	if err != nil {
		t.Fatal(err)
	}
	body := string(b)
	if strings.Contains(body, "`scratch/`") {
		t.Error("config ignore name still listed")
	}
	if !strings.Contains(body, "`cmd/`") {
		t.Error("normal directory missing from map")
	}
	for _, always := range []string{"`.git/`", "`.metadata/`"} {
		if strings.Contains(body, always) {
			t.Errorf("%s must be skipped by default", always)
		}
	}
}

func TestProjectMapGolden(t *testing.T) {
	p := fixture(t)
	if err := Build(p, []string{"scratch"}); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(p.Path, ".metadata", "agent", "PROJECT_MAP.md"))
	if err != nil {
		t.Fatal(err)
	}
	golden := filepath.Join("testdata", "project_map.golden")
	if *update {
		if err := os.MkdirAll("testdata", 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(golden, got, 0644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("read golden (run with -update to create): %v", err)
	}
	// Golden files may check out with CRLF on Windows; generated content
	// always uses LF — compare normalized so all three OSes agree.
	want = []byte(strings.ReplaceAll(string(want), "\r\n", "\n"))
	if string(got) != string(want) {
		t.Errorf("PROJECT_MAP.md mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestDiffMarksChangedLines(t *testing.T) {
	got := Diff("a\nb\nc\n", "a\nx\nc\n")
	want := []string{"  a", "- b", "+ x", "  c"}
	if len(got) != len(want) {
		t.Fatalf("Diff = %#v, want %#v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("Diff[%d] = %q, want %q (full %#v)", i, got[i], want[i], got)
		}
	}
	if got := Diff("", "one\n"); len(got) != 1 || got[0] != "+ one" {
		t.Fatalf("Diff(empty, one) = %#v, want every line added", got)
	}
	if got := Diff("same\n", "same\n"); len(got) != 1 || got[0] != "  same" {
		t.Fatalf("Diff(identical) = %#v, want context only", got)
	}
}
