package mapgen

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/manojpisini/rivu/internal/registry"
)

var update = flag.Bool("update", false, "rewrite golden files")

func fixture(t *testing.T) registry.Project {
	t.Helper()
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "README.md"), []byte("# Golden\n\nA tiny fixture project used to pin PROJECT_MAP.md.\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "main.go"), []byte("package x\n"), 0644); err != nil {
		t.Fatal(err)
	}
	for _, d := range []string{"cmd", ".git", "scratch"} {
		if err := os.MkdirAll(filepath.Join(root, d), 0755); err != nil {
			t.Fatal(err)
		}
	}
	return registry.Project{Name: "Golden", Slug: "golden", Path: root, Stack: []string{"go"}}
}

func TestBuildPreservesAgentsMD(t *testing.T) {
	p := fixture(t)
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	agents := filepath.Join(p.Path, ".metadata", "agent", "AGENTS.md")
	if err := os.WriteFile(agents, []byte("hand-written rules"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(agents)
	if string(got) != "hand-written rules" {
		t.Errorf("AGENTS.md overwritten: %q", got)
	}
}

func TestProjectMapHeaderHashAndSkipRewrite(t *testing.T) {
	p := fixture(t)
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	mapPath := filepath.Join(p.Path, ".metadata", "agent", "PROJECT_MAP.md")
	first, err := os.ReadFile(mapPath)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(string(first), "<!-- generated by rivu - do not edit -->\n<!-- content-hash: ") {
		t.Errorf("missing generated header: %q", string(first[:80]))
	}
	// Unchanged content: no rewrite.
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	second, _ := os.ReadFile(mapPath)
	if string(second) != string(first) {
		t.Error("unchanged map was rewritten")
	}
	// Changed content: rewritten with a new hash.
	if err := os.WriteFile(filepath.Join(p.Path, "new.go"), []byte("package x\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	third, _ := os.ReadFile(mapPath)
	if string(third) == string(first) {
		t.Error("map did not update after project changed")
	}
}

func TestStatusMirrorsBuild(t *testing.T) {
	p := fixture(t)
	missing, stale := Status(p, nil)
	if !missing || !stale {
		t.Errorf("before build: missing=%v stale=%v, want both true", missing, stale)
	}
	if err := Build(p, nil); err != nil {
		t.Fatal(err)
	}
	if missing, stale = Status(p, nil); missing || stale {
		t.Errorf("after build: missing=%v stale=%v, want both false", missing, stale)
	}
	if err := os.WriteFile(filepath.Join(p.Path, "extra.go"), []byte("package x\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if _, stale = Status(p, nil); !stale {
		t.Error("new file did not make the map stale")
	}
	// Status never writes.
	agents := filepath.Join(p.Path, ".metadata", "agent", "AGENTS.md")
	if err := os.Remove(agents); err != nil {
		t.Fatal(err)
	}
	if missing, _ = Status(p, nil); !missing {
		t.Error("missing AGENTS.md not reported")
	}
	if _, err := os.Stat(agents); err == nil {
		t.Error("Status wrote AGENTS.md")
	}
}

func TestBuildSharesIgnoreList(t *testing.T) {
	p := fixture(t)
	if err := Build(p, []string{"scratch"}); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(filepath.Join(p.Path, ".metadata", "agent", "PROJECT_MAP.md"))
	if err != nil {
		t.Fatal(err)
	}
	body := string(b)
	if strings.Contains(body, "`scratch/`") {
		t.Error("config ignore name still listed")
	}
	if !strings.Contains(body, "`cmd/`") {
		t.Error("normal directory missing from map")
	}
	for _, always := range []string{"`.git/`", "`.metadata/`"} {
		if strings.Contains(body, always) {
			t.Errorf("%s must be skipped by default", always)
		}
	}
}

func TestProjectMapGolden(t *testing.T) {
	p := fixture(t)
	if err := Build(p, []string{"scratch"}); err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join(p.Path, ".metadata", "agent", "PROJECT_MAP.md"))
	if err != nil {
		t.Fatal(err)
	}
	golden := filepath.Join("testdata", "project_map.golden")
	if *update {
		if err := os.MkdirAll("testdata", 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(golden, got, 0644); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(golden)
	if err != nil {
		t.Fatalf("read golden (run with -update to create): %v", err)
	}
	// Golden files may check out with CRLF on Windows; generated content
	// always uses LF — compare normalized so all three OSes agree.
	want = []byte(strings.ReplaceAll(string(want), "\r\n", "\n"))
	if string(got) != string(want) {
		t.Errorf("PROJECT_MAP.md mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

func TestDiffMarksChangedLines(t *testing.T) {
	got := Diff("a\nb\nc\n", "a\nx\nc\n")
	want := []string{"  a", "- b", "+ x", "  c"}
	if len(got) != len(want) {
		t.Fatalf("Diff = %#v, want %#v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("Diff[%d] = %q, want %q (full %#v)", i, got[i], want[i], got)
		}
	}
	if got := Diff("", "one\n"); len(got) != 1 || got[0] != "+ one" {
		t.Fatalf("Diff(empty, one) = %#v, want every line added", got)
	}
	if got := Diff("same\n", "same\n"); len(got) != 1 || got[0] != "  same" {
		t.Fatalf("Diff(identical) = %#v, want context only", got)
	}
}

// section returns the body between two `## ` headers of a PROJECT_MAP.
func section(t *testing.T, body, header string) string {
	t.Helper()
	i := strings.Index(body, header)
	if i < 0 {
		t.Fatalf("no %q section in:\n%s", header, body)
	}
	rest := body[i+len(header):]
	if j := strings.Index(rest, "\n## "); j >= 0 {
		rest = rest[:j]
	}
	return strings.TrimSpace(rest)
}

func TestReadmePurpose(t *testing.T) {
	cases := []struct {
		name string
		body string
		want string
	}{
		{"no readme", "", ""},
		{"heading badge paragraph", "# Tool\n\n[![CI](https://img.shields.io/x)](https://ci)\n\nShip things.\n\nMore below.\n", "Ship things."},
		{"plain first paragraph", "line one\nline two\n\nline three\n", "line one line two"},
		{"heading only", "# Tool\n\n", ""},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := t.TempDir()
			if tc.body != "" {
				if err := os.WriteFile(filepath.Join(root, "README.md"), []byte(tc.body), 0644); err != nil {
					t.Fatal(err)
				}
			}
			if got := readmePurpose(root); got != tc.want {
				t.Errorf("purpose = %q, want %q", got, tc.want)
			}
		})
	}
	// Truncation keeps the purpose inside the ceiling and marks the cut.
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "README.md"), []byte(strings.Repeat("word ", 80)+"\n"), 0644); err != nil {
		t.Fatal(err)
	}
	if got := readmePurpose(root); !strings.HasSuffix(got, "…") || len([]rune(got)) > 241 {
		t.Errorf("truncated purpose = %q", got)
	}
}

// TestContentRanksAndExtracts (M-02): entrypoints/manifests/CI/build/
// tests rank first, README supplies the purpose, go.mod the module,
// and package.json scripts plus Makefile targets are extracted.
func TestContentRanksAndExtracts(t *testing.T) {
	root := t.TempDir()
	write := func(path, body string) {
		t.Helper()
		if err := os.MkdirAll(filepath.Dir(filepath.Join(root, path)), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, path), []byte(body), 0644); err != nil {
			t.Fatal(err)
		}
	}
	write("README.md", "# Tool\n\n[![CI](https://img.shields.io/x)](https://ci)\n\nShip things without melting down.\n\nMore below.\n")
	write("main.py", "print(1)\n")
	write("notes.md", "scratch\n")
	write("go.mod", "module example.com/shipper\ngo 1.24\n")
	write("package.json", `{"scripts":{"build":"tsc","test":"vitest"}}`+"\n")
	write("Makefile", ".PHONY: lint\nlint:\n\tgo vet ./...\nrelease: build\n\techo hi\nVAR := 1\n")
	write("cmd/shipper/main.go", "package main\n")
	write("scripts/deploy.sh", "echo hi\n")
	write(".github/workflows/ci.yml", "name: ci\n")
	write("tests/test_x.py", "def test_x(): pass\n")
	p := registry.Project{Name: "Shipper", Slug: "shipper", Path: root, Stack: []string{"python"}}
	agents, body := Content(p, nil)

	wantPurpose := "Ship things without melting down."
	if got := section(t, body, "## Purpose"); got != wantPurpose {
		t.Errorf("Purpose = %q, want %q", got, wantPurpose)
	}
	if !strings.Contains(agents, "## Project purpose\n"+wantPurpose+"\n") {
		t.Errorf("AGENTS purpose not taken from README:\n%s", agents)
	}
	if stack := section(t, body, "## Stack"); !strings.Contains(stack, "module `example.com/shipper`") {
		t.Errorf("Stack = %q, want go.mod module", stack)
	}
	scripts := section(t, body, "## Scripts and targets")
	for _, want := range []string{"npm run build", "npm run test", "make lint", "make release"} {
		if !strings.Contains(scripts, want) {
			t.Errorf("scripts = %q, missing %q", scripts, want)
		}
	}
	if strings.Contains(scripts, "PHONY") || strings.Contains(scripts, "VAR") {
		t.Errorf("scripts leaked make syntax: %q", scripts)
	}
	files := section(t, body, "## Important files")
	prev := -1
	for _, want := range []string{"`cmd/shipper/main.go`", "`main.py`", "`go.mod`", "`package.json`", "`Makefile`", "`README.md`", "`notes.md`"} {
		i := strings.Index(files, want)
		if i < 0 {
			t.Fatalf("files missing %s:\n%s", want, files)
		}
		if i < prev {
			t.Errorf("%s out of rank order:\n%s", want, files)
		}
		prev = i
	}
	dirs := section(t, body, "## Important directories")
	prev = -1
	for _, want := range []string{"`cmd/`", "`.github/`", "`scripts/`", "`tests/`"} {
		i := strings.Index(dirs, want)
		if i < 0 {
			t.Fatalf("dirs missing %s:\n%s", want, dirs)
		}
		if i < prev {
			t.Errorf("%s out of rank order:\n%s", want, dirs)
		}
		prev = i
	}
}

// TestSecretsListedByNameOnly (M-03): secret files are named under
// "Do not read / never commit", dropped from Important files, and
// their contents never reach the map (spec 4.4 rule 6).
func TestSecretsListedByNameOnly(t *testing.T) {
	root := t.TempDir()
	secrets := map[string]string{
		".env":         "API_TOKEN=supersecret\n",
		".env.local":   "OTHER=1\n",
		"server.pem":   "-----BEGIN CERT-----\n",
		"id_rsa":       "PRIVATE KEY MATERIAL\n",
		"api.key":      "k=1\n",
		"secrets.json": `{"pw":"hunter2"}`,
	}
	for name, body := range secrets {
		if err := os.WriteFile(filepath.Join(root, name), []byte(body), 0644); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(root, "notes.md"), []byte("fine\n"), 0644); err != nil {
		t.Fatal(err)
	}
	_, body := Content(registry.Project{Name: "P", Slug: "p", Path: root}, nil)

	sec := section(t, body, "## Do not read / never commit")
	for name := range secrets {
		if !strings.Contains(sec, "`"+name+"`") {
			t.Errorf("section missing %s:\n%s", name, sec)
		}
	}
	for _, pat := range []string{".env*", "*.pem", "id_rsa*", "*.key", "secrets.*"} {
		if !strings.Contains(sec, pat) {
			t.Errorf("section missing pattern %s:\n%s", pat, sec)
		}
	}
	files := section(t, body, "## Important files")
	for name := range secrets {
		if strings.Contains(files, "`"+name+"`") {
			t.Errorf("secret %s still listed as important reading:\n%s", name, files)
		}
	}
	if !strings.Contains(files, "`notes.md`") {
		t.Errorf("normal file missing:\n%s", files)
	}
	for _, leak := range []string{"supersecret", "hunter2", "PRIVATE KEY", "BEGIN CERT"} {
		if strings.Contains(body, leak) {
			t.Fatalf("map inlined secret contents: %q", leak)
		}
	}
}

// TestSafeCommandsFromToolchain (M-04): AGENTS.md Safe commands names
// real test entrypoints per detected manifest, with the generic prose
// only as the fallback when nothing is detected.
func TestSafeCommandsFromToolchain(t *testing.T) {
	cases := []struct {
		name  string
		files map[string]string
		want  []string
		bad   []string
	}{
		{"go", map[string]string{"go.mod": "module x\ngo 1.24\n"}, []string{"`go test ./...`"}, nil},
		{"node with test script", map[string]string{"package.json": `{"scripts":{"test":"vitest"}}` + "\n"}, []string{"`npm test`"}, nil},
		{"node without test script", map[string]string{"package.json": `{"scripts":{"build":"tsc"}}` + "\n"}, nil, []string{"npm test"}},
		{"rust", map[string]string{"Cargo.toml": "[package]\nname = \"x\"\n"}, []string{"`cargo test`"}, nil},
		{"make test target", map[string]string{"Makefile": "test:\n\tgo test ./...\n"}, []string{"`make test`"}, nil},
		{"nothing detected", map[string]string{}, nil, nil},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			root := t.TempDir()
			for name, body := range tc.files {
				if err := os.WriteFile(filepath.Join(root, name), []byte(body), 0644); err != nil {
					t.Fatal(err)
				}
			}
			agents, _ := Content(registry.Project{Name: "P", Slug: "p", Path: root}, nil)
			i := strings.Index(agents, "## Safe commands")
			if i < 0 {
				t.Fatal("no Safe commands section")
			}
			safe := agents[i:]
			for _, want := range tc.want {
				if !strings.Contains(safe, want) {
					t.Errorf("Safe commands missing %s:\n%s", want, safe)
				}
			}
			for _, bad := range tc.bad {
				if strings.Contains(safe, bad) {
					t.Errorf("Safe commands should not contain %q:\n%s", bad, safe)
				}
			}
			if len(tc.want) == 0 && !strings.Contains(safe, "Inspect project scripts") {
				t.Errorf("fallback prose missing:\n%s", safe)
			}
		})
	}
}
