package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/manojpisini/rivu/internal/cli"
	"github.com/manojpisini/rivu/internal/registry"
	"github.com/manojpisini/rivu/internal/service"
)

// TestE2EHeadless drives the real command tree in-process against an
// isolated RIVU_HOME: init (config + DB), scan, source, list, flow, doctor,
// agent sync, then verifies registry state and files end to end.
func TestE2EHeadless(t *testing.T) {
	home := t.TempDir()
	t.Setenv("RIVU_HOME", home)
	t.Setenv("RIVU_CONFIG", "")
	ws := filepath.Join(home, "ws")
	if err := os.MkdirAll(ws, 0755); err != nil {
		t.Fatal(err)
	}
	// The config must exist before the first command: defaults point at
	// the real ~/Projects and tests must never touch it.
	cfg := fmt.Sprintf("[workspace]\nroot = %q\n", ws)
	if err := os.WriteFile(filepath.Join(home, "config.toml"), []byte(cfg), 0644); err != nil {
		t.Fatal(err)
	}

	run := func(args ...string) {
		t.Helper()
		r := cli.Root("test", "dev", "unknown")
		r.SetArgs(args)
		r.SetOut(io.Discard)
		r.SetErr(io.Discard)
		if err := r.Execute(); err != nil {
			t.Fatalf("rivu %s: %v", strings.Join(args, " "), err)
		}
	}

	run("config", "show")
	run("scan")
	run("source", "e2e-demo", "--git=false")
	run("list")
	run("flow", "e2e-demo", "--to", "active", "--yes")
	run("doctor", "e2e-demo")
	run("agent", "sync", "e2e-demo")
	run("scan")
	run("stats")

	a, err := service.Open()
	if err != nil {
		t.Fatalf("Open: %v", err)
	}
	defer a.Close()

	p, err := a.Registry.Resolve("e2e-demo")
	if err != nil {
		t.Fatalf("resolve: %v", err)
	}
	if p.FlowStage != "active" {
		t.Errorf("flow_stage = %q, want active", p.FlowStage)
	}
	if p.Channel != registry.ChannelForFlow("active") {
		t.Errorf("channel = %q, want %q", p.Channel, registry.ChannelForFlow("active"))
	}
	if !p.OnDisk {
		t.Error("project must be on disk after flow + rescan")
	}
	if !p.HasBank || !p.HasMap {
		t.Errorf("flags: bank=%v map=%v, want both true after agent sync", p.HasBank, p.HasMap)
	}
	mapPath := filepath.Join(p.Path, ".metadata", "agent", "PROJECT_MAP.md")
	body, err := os.ReadFile(mapPath)
	if err != nil {
		t.Fatalf("PROJECT_MAP.md: %v", err)
	}
	if !strings.Contains(string(body), "generated by rivu") {
		t.Error("PROJECT_MAP.md missing generated header")
	}
	tomlBody, err := os.ReadFile(filepath.Join(p.Path, ".metadata", "project.toml"))
	if err != nil {
		t.Fatalf("project.toml: %v", err)
	}
	if !strings.Contains(string(tomlBody), "active") {
		t.Errorf("project.toml missing active stage:\n%s", tomlBody)
	}

	st, err := a.Registry.States()
	if err != nil {
		t.Fatal(err)
	}
	if len(st.Missing) != 0 || len(st.Unregistered) != 0 || len(st.StageMismatch) != 0 {
		t.Errorf("mismatch states after e2e: missing=%d unregistered=%d stage-mismatch=%d",
			len(st.Missing), len(st.Unregistered), len(st.StageMismatch))
	}
}
