package cli

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

//go:embed cliref.md
var clirefIntro string

// writeCliReference writes dir/cli.md: the hand-maintained intro (the
// embedded cliref.md — contract, JSON schemas, environment) followed by a
// command reference generated from the cobra tree, so per-command docs
// cannot drift from --help. Only this file's Commands section is generated.
func writeCliReference(root *cobra.Command, dir string) error {
	var b strings.Builder
	b.WriteString(clirefIntro)
	b.WriteString("\n## Commands\n\n")
	b.WriteString("_Generated from the command tree by `rivu docs` — do not edit this section._\n\n")
	var walk func(*cobra.Command)
	walk = func(c *cobra.Command) {
		if c != root && (!c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand()) {
			return
		}
		_ = doc.GenMarkdownCustom(c, &b, cliAnchor)
		for _, sub := range c.Commands() {
			walk(sub)
		}
	}
	walk(root)
	var kept []string
	for _, line := range strings.Split(b.String(), "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "###### Auto generated by spf13/cobra") {
			continue
		}
		kept = append(kept, line)
	}
	return os.WriteFile(filepath.Join(dir, "cli.md"), []byte(strings.Join(kept, "\n")), 0644)
}

// cliAnchor rewrites cobra's rivu_scan.md style links into in-page anchors
// (#rivu-scan) so the single-file reference navigates on GitHub.
func cliAnchor(s string) string {
	return "#" + strings.ToLower(strings.ReplaceAll(strings.TrimSuffix(s, ".md"), "_", "-"))
}

func docsCmd() *cobra.Command {
	var dir string
	c := &cobra.Command{
		Use:    "docs",
		Hidden: true,
		Args:   cobra.NoArgs,
		Short:  "Generate man pages and markdown help",
		Long: `Write a man page (*.1) and a markdown file for every command
into --dir (default: docs/), plus cli.md: the scripting reference
(intro embedded from internal/cli/cliref.md + a command reference
generated from the command tree). Hidden from help, for packagers
and the docs pipeline.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := os.MkdirAll(dir, 0755); err != nil {
				return fmt.Errorf("create %s: %w", dir, err)
			}
			root := cmd.Root()
			if err := doc.GenManTree(root, nil, dir); err != nil {
				return fmt.Errorf("generate man pages: %w", err)
			}
			if err := doc.GenMarkdownTree(root, dir); err != nil {
				return fmt.Errorf("generate markdown: %w", err)
			}
			if err := writeCliReference(root, dir); err != nil {
				return fmt.Errorf("write cli.md: %w", err)
			}
			entries, err := os.ReadDir(dir)
			if err != nil {
				return err
			}
			var man, md int
			for _, e := range entries {
				switch {
				case strings.HasSuffix(e.Name(), ".1"):
					man++
				case strings.HasSuffix(e.Name(), ".md"):
					md++
				}
			}
			fmt.Fprintf(os.Stderr, "wrote %d man page(s) and %d markdown file(s) to %s\n", man, md, filepath.Clean(dir))
			return nil
		},
	}
	c.Flags().StringVar(&dir, "dir", "docs", "output directory")
	return c
}
